service: extension-wallet-backend
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource: "arn:aws:dynamodb:*:*:*"
  environment:
    USERS_TABLE: users-table-${opt:stage, self:provider.stage}
    WALLETS_TABLE: wallets-table-${opt:stage, self:provider.stage}
    OFFERS_TABLE: extension-offers-${opt:stage, self:provider.stage}
    NOTIFICATIONS_TABLE: extension-notifications-${opt:stage, self:provider.stage}
    NEAR_USERS_API_URL: "https://api.nearlogin.io"
    ACCESS_TOKEN_SECRET: "5d3e6e0d8eebc0d744801ff0e8d37cd91b24a5bb5f517e51736ec83522340205938e498b2d92e9f6e17ee77227c92508722a9039e417ef2e7eecfc3611fd68f4"
    REFRESH_TOKEN_SECRET: "a610f4cfe57fcd7460ef697da52e03a2c74c53f6d2cd7e2d08bbf115693e9ba2a716ae87da96d52d375e17c4488e97de29b69cb077ad03c16b65e249d81ab80c"

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

useDotenv: true
